// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: blockchain/proto/blockchain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockchainFullNodeClient is the client API for BlockchainFullNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainFullNodeClient interface {
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	AppendBlocks(ctx context.Context, in *AppendBlocksRequest, opts ...grpc.CallOption) (*AppendBlocksResponse, error)
}

type blockchainFullNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainFullNodeClient(cc grpc.ClientConnInterface) BlockchainFullNodeClient {
	return &blockchainFullNodeClient{cc}
}

func (c *blockchainFullNodeClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, "/blockchain.BlockchainFullNode/GetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainFullNodeClient) AppendBlocks(ctx context.Context, in *AppendBlocksRequest, opts ...grpc.CallOption) (*AppendBlocksResponse, error) {
	out := new(AppendBlocksResponse)
	err := c.cc.Invoke(ctx, "/blockchain.BlockchainFullNode/AppendBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainFullNodeServer is the server API for BlockchainFullNode service.
// All implementations must embed UnimplementedBlockchainFullNodeServer
// for forward compatibility
type BlockchainFullNodeServer interface {
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	AppendBlocks(context.Context, *AppendBlocksRequest) (*AppendBlocksResponse, error)
	mustEmbedUnimplementedBlockchainFullNodeServer()
}

// UnimplementedBlockchainFullNodeServer must be embedded to have forward compatible implementations.
type UnimplementedBlockchainFullNodeServer struct {
}

func (UnimplementedBlockchainFullNodeServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedBlockchainFullNodeServer) AppendBlocks(context.Context, *AppendBlocksRequest) (*AppendBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendBlocks not implemented")
}
func (UnimplementedBlockchainFullNodeServer) mustEmbedUnimplementedBlockchainFullNodeServer() {}

// UnsafeBlockchainFullNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainFullNodeServer will
// result in compilation errors.
type UnsafeBlockchainFullNodeServer interface {
	mustEmbedUnimplementedBlockchainFullNodeServer()
}

func RegisterBlockchainFullNodeServer(s grpc.ServiceRegistrar, srv BlockchainFullNodeServer) {
	s.RegisterService(&BlockchainFullNode_ServiceDesc, srv)
}

func _BlockchainFullNode_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainFullNodeServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.BlockchainFullNode/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainFullNodeServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainFullNode_AppendBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainFullNodeServer).AppendBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.BlockchainFullNode/AppendBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainFullNodeServer).AppendBlocks(ctx, req.(*AppendBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainFullNode_ServiceDesc is the grpc.ServiceDesc for BlockchainFullNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainFullNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.BlockchainFullNode",
	HandlerType: (*BlockchainFullNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlocks",
			Handler:    _BlockchainFullNode_GetBlocks_Handler,
		},
		{
			MethodName: "AppendBlocks",
			Handler:    _BlockchainFullNode_AppendBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain/proto/blockchain.proto",
}
